routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('contacts', 'ContactController');

app/Contact.php
<?php
namespace App;

use Illuminate\Database\Eloquent\Model;

use App\Events\UserHasContacted; 

class Contact extends Model
{
    public $timestamps = false;

    protected $table      = 'contact';
    protected $primaryKey = 'contactId';

    protected $fillable = ['contactId', 'countryId', 'userId', 'contactCode', 'contactName',
        'contactAddress', 'contactPhone', 'contactEmail', 'dateCreated', 'lastUserId'];

//--------------------------------------------------------------------
    /** Relations */
//--------------------------------------------------------------------
    public function user()
    {
        return $this->hasOne('App\User', 'userId', 'userId');
    }

//--------------------------------------------------------------------
    /** Query Scope  */
//--------------------------------------------------------------------
    //nombre codigo direccion
    public function scopeFilter($query, $filteredOut)
    {
        if ($filteredOut) {
            return $query->where('firstName', 'LIKE', "%$filteredOut%")
                         ->orWhere('lastName', 'LIKE', "%$filteredOut%")
                         ->orWhere('email', 'LIKE', "%$filteredOut%")
                         ->orWhere('contactNumber', 'LIKE', "%$filteredOut%");
        }
    }

//--------------------------------------------------------------------
    /** Function of Models */
//--------------------------------------------------------------------
    public function getAll($filteredOut)
    {
        return $this->orderBy('contactId', 'ASC')
                    ->filter($filteredOut)
                    ->paginate(10);
    }
//------------------------------------------
    public function findById($contactId)
    {
        return $this->where('contactId', '=', $contactId)
                    ->get();
    }
//------------------------------------------
    public function insertContact($data)
    {
    
        $contact                  = new Contact;
        $contact->firstName       =  strtoupper($data['firstName']);
        $contact->lastName        =  strtoupper($data['lastName']);
        $contact->email           = strtolower($data['email']);
        $contact->contactNumber   = $data['contactNumber'];
        $contact->save();

        UserHasContacted::dispatch($data);

        return $contact;
    }
//------------------------------------------
    public function updateContact($contactId,$data)
    {
       $contactUpdated =   $this->where('contactId', $contactId)->update(array(
            'firstName'    => $data['firstName'],
            'lastName'      => $data['lastName'],
            'email'         => $data['email'],
            'contactNumber'  => $data['contactNumber'],
        ));

        return $contactUpdated;

    }
//------------------------------------------
    public function deleteContact($contactId)
    {

          $this->where('contactId', '=', $contactId)->delete();

    }
//------------------------------------------

    
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/ContactController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Contact;


class ContactController extends Controller
{
      private $oContact;

    public function __construct()
    {
        $this->middleware('auth');
        $this->oContact = new Contact;
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('contactNew');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
       $validatedData = $request->validate([
           'firstName' => 'required|string|max:60',
           'lastName' => 'required|string|max:60',
           'email' => 'required|unique:contact,email',
           'contactNumber' => 'required',
          ]);

      $contact = $this->oContact->insertContact($request->all());
      
   
            
        $notification = array(
            'message'    => 'Contact Created'.$contact->clientCode,
            'alert-type' => 'success',
        );

        return redirect()->route('home')->with($notification);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($contactId)
    {

          // $countrys = Country::all();
        $contact = $this->oContact->findById($contactId);

        return view('contactNew', compact('contact'));
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update($contactId,Request $request)
    {
         $this->oContact->updateContact($contactId,$request->all());

        $notification = array(
            'message'    => 'Contact Modified',
            'alert-type' => 'success',
        );
        return redirect()->route('home')
            ->with($notification);
    }

  /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($contactId)
    {

       $rs = $this->oContact->deleteContact($contactId);

         $notification = array(
            'alert-type' => 'info',
            'message'    => 'Contact Deleted',
        );

        return redirect()->route('home')->with($notification);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;
use App\Contact;

use Illuminate\Http\Request;

class HomeController extends Controller
{
     private $oContact;

    public function __construct()
    {
        $this->middleware('auth');
        $this->oContact = new Contact;
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $contacts = $this->oContact->getAll($request->filteredOut);
        return view('home', compact('contacts'));
    }
}

resources/views/contactNew.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                  <div class="text-right">
                    <a class="btn btn-warning" href="{{route('home')}}">Return</a>
                  </div>
@if( isset($contact) )
               <div class="panel-heading"><h4 class="text-center">Update Contact</h4></div>
@else
               <div class="panel-heading"><h4 class="text-center">New Contact</h4></div>
@endif

       @if ($errors->any())
          <div class="alert alert-danger">
              <h4>Errors:</h4>
              <ul>
                  @foreach ($errors->all() as $error)
                      <li>{{ $error }}</li>
                  @endforeach
              </ul>
          </div>
      @endif
@if( isset($contact) )
<form class="form" action="{{Route('contacts.update',['id' => $contact[0]->contactId])}}" method="POST">
        {{method_field('PUT')}}
@else
<form class="form" action="{{Route('contacts.store')}}" method="POST">
@endif

        {{csrf_field()}}
  <div class="form-group">
    <label for="field1">First Name</label>
    <input type="text" class="form-control" id="field1" name="firstName" value="{{ old('firstName', $contact[0]->firstName ?? null) }}" placeholder="">
  </div>
  <div class="form-group">
    <label for="field2">Last Name</label>
    <input type="text" class="form-control" id="field2"  name="lastName" value="{{ old('lastName', $contact[0]->lastName ?? null) }}" placeholder="">
  </div>
    <div class="form-group">
    <label for="field3">Email</label>
    <input type="email" class="form-control" id="field3" name="email" value="{{ old('email', $contact[0]->email ?? null) }}" placeholder="email@example.com">
  </div>
    <div class="form-group">
    <label for="field4">Contact Number</label>
    <input type="text" class="form-control" id="field4" name="contactNumber" value="{{ old('contactNumber', $contact[0]->contactNumber ?? null) }}" placeholder="(xxx) xxx-xxxx">
  </div>
@if( isset($contact) )
               <div class="text-center"><button type="submit" class="btn btn-info">Update</button></div>
@else
               <div class="text-center"><button type="submit" class="btn btn-primary">Submit</button></div>
@endif
</form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                  <div class="text-right">
                    <a class="btn btn-primary" href="{{route('contacts.create')}}">New Contact</a>
                  </div>


   <div class="row">
      <div class="col-xs-12 text-center">
      <form class="form-inline" action="{{Route('home')}}" method="GET">

         <div class="form-group">
           <label for="filteredOut"></label>
           <input type="text" class="form-control" name="filteredOut" id="filteredOut" placeholder="Write data..." autocomplete="off">
         </div>

          <button type="submit" class="btn btn-info" > Search
           </button>
        </form>
      </div>
    </div>

<div class="panel-heading"><h4 class="text-center">Contacts List</h4></div>
<div class="table-responsive">
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">First Name</th>
      <th scope="col">Last Name</th>
      <th scope="col">Email</th>
      <th scope="col">Contact Number</th>
      <th scope="col">Options</th>
    </tr>
  </thead>
  <tbody>

@php $acum=0 @endphp
@foreach($contacts as $contact)
    <tr>
      <th scope="row">{{++$acum}}</th>
      <td>{{$contact->firstName}}</td>
      <td>{{$contact->lastName}}</td>
      <td>{{$contact->email}}</td>
      <td>{{$contact->contactNumber}}</td>
      <td>       
        <a href="{{route('contacts.edit', ['id' => $contact->contactId])}}" class="btn btn-warning btn-sm">
                        EDIT
          </a> 
             <a href="#" class="btn btn-danger btn-sm" onclick="event.preventDefault();document.getElementById('delete-form'+{{$contact->contactId}}).submit();">
                                            DELETE 
                 </a>
              <form id="delete-form{{$contact->contactId}}" action="{{route('contacts.destroy', ['id' => $contact->contactId])}}" method="POST" style="display: none;">
                     {{ csrf_field() }}
                     {{ method_field('DELETE') }}
                 </form>
          </td>
    </tr>
@endforeach

  </tbody>
</table>
</div>
            <div class="text-center">
                {{$contacts->render()}}
            </div>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.css">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse" aria-expanded="false">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @guest
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>  
 // show alert notifications
    @if(Session::has('message'))
        var type = "{{ Session::get('alert-type', 'info') }}";
        switch(type){
            case 'info':
                toastr.info("{{ Session::get('message') }}");
                break;
            case 'warning':
                toastr.warning("{{ Session::get('message') }}");
                break;
            case 'success':
                toastr.success("{{ Session::get('message') }}");
                break;
            case 'error':
                toastr.error("{{ Session::get('message') }}");
                break;
        }
    @endif
    </script>
</body>
</html>